cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^remove/(?P<product_slug>[-\w]+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<big_category_slug>[-\w]+)/(?P<slug>[-\w]+)/', views.CartAdd, name='CartAdd'),
    url(r'^versus/remove/(?P<product_slug>[-\w]+)/$', views.VersusRemove, name='VersusRemove'),
    url(r'^versus/add/(?P<big_category_slug>[-\w]+)/(?P<slug>[-\w]+)/', views.VersusAdd, name='VersusAdd'),
    url(r'^versus/$', views.VersusDetail, name='VersusDetail'),
    url(r'^craft/remove/(?P<big_category_slug>[-\w]+)/(?P<product_slug>[-\w]+)/$', views.CraftRemove, name='CraftRemove'),
    url(r'^craft/add/(?P<big_category_slug>[-\w]+)/(?P<category_slug>[-\w]+)/(?P<slug>[-\w]+)/', views.CraftAdd, name='CraftAdd'),
    url(r'^craft/$', views.CraftDetail, name='CraftDetail'),
    url(r'^$', views.CartDetail, name='CartDetail')


]

main/urls.py
from . import views
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .decorators import check_recaptcha

urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.NotebookSList, name='NotebookSListByCategory'),
    url(r'^(?P<big_category_slug>[-\w]+)/(?P<category_slug>[-\w]+)/(?P<slug>[-\w]+)/$', check_recaptcha(views.ProductDetail), name='ProductDetail')
]

myshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import main.views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^about_us/', main.views.about_us),
    url(r'^cart/', include('cart.urls', namespace="cart")),
    url(r'^', include('main.urls', namespace='main')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]
class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, label='Количество', widget=forms.NumberInput(attrs={'class':'bra', 'value':'1'}))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

main/forms.py
from django import forms

class ChoisListForm(forms.Form):
    chos=forms.BooleanField(required=False, initial=False,)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from main.models import Notebook, Complecting, Acses, Perf, PC, PCForm
from .cart import Cart, Versus, Craft
from .forms import CartAddProductForm
from decimal import Decimal


@require_POST
def CartAdd(request, big_category_slug, slug):
    cart = Cart(request)
    if big_category_slug == 'notebooks':
        product = get_object_or_404(Notebook, slug=slug, available=True)
    elif big_category_slug == 'komplektuyushie':
        product = get_object_or_404(Complecting, slug=slug, available=True)
    elif big_category_slug == 'acses':
        product = get_object_or_404(Acses, slug=slug, available=True)
    elif big_category_slug == 'perf':
        product = get_object_or_404(Perf, slug=slug, available=True)
    elif big_category_slug == 'kompyutery':
        product = get_object_or_404(PC, slug=slug, available=True)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:CartDetail')


def CartRemove(request, product_slug):
    cart = Cart(request)
    cart.remove(product_slug)
    return redirect('cart:CartDetail')


def CartDetail(request):
    cart = Cart(request)
    title = 'Корзина - PCShop.uz'
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={
                'quantity': item['quantity'],
                'update': True
            })

    for popular_c in cart:
        if popular_c['big_cat'] == 'notebooks':
            var_c = get_object_or_404(Notebook, slug=popular_c['slug'])
            cart.cart[popular_c['slug']]['product'] = var_c
        elif popular_c['big_cat'] == 'komplektuyushie':
            var_c = get_object_or_404(Complecting, slug=popular_c['slug'])
            cart.cart[popular_c['slug']]['product'] = var_c
        elif popular_c['big_cat'] == 'acses':
            var_c = get_object_or_404(Acses, slug=popular_c['slug'])
            cart.cart[popular_c['slug']]['product'] = var_c
        elif popular_c['big_cat'] == 'perf':
            var_c = get_object_or_404(Perf, slug=popular_c['slug'])
            cart.cart[popular_c['slug']]['product'] = var_c
        elif popular_c['big_cat'] == 'kompyutery':
            var_c = get_object_or_404(PC, slug=popular_c['slug'])
            cart.cart[popular_c['slug']]['product'] = var_c

    for item in cart.cart.values():
        item['price'] = Decimal(item['price'])
        item['total_price'] = item['price'] * item['quantity']

    total_price = int(cart.get_total_price())

    return render(request, '../../main/templates/cart.html', {'cart_t': cart,
                                                              'vs': cart.cart,
                                                              'title': title,
                                                              'total_price': total_price,
                                                              'test': cart})


def VersusAdd(request, big_category_slug, slug):
    versus = Versus(request)
    versus.versus_add(product=slug, big_category_slug=big_category_slug)
    return redirect('cart:VersusDetail')


def VersusRemove(request, product_slug):
    versus = Versus(request)
    versus.remove(product_slug)
    return redirect('cart:VersusDetail')


def VersusDetail(request):
    versus = Versus(request)
    var_v = list()
    link_v = list()
    vs = list()
    for popular_c in versus:
        if 'category' in popular_c:
           if popular_c['category'] == 'notebooks':
               product_c = Notebook.objects.filter(slug= popular_c['name'])
               var_v += list(product_c)
               var_c = get_object_or_404(Notebook, slug= popular_c['name'])
               var_b = var_c.get_absolute_url
               link_v.append(var_b)
           elif popular_c['category'] == 'komplektuyushie':
               product_c = Complecting.objects.filter(slug= popular_c['name'])
               var_v += list(product_c)
               var_c = get_object_or_404(Complecting, slug= popular_c['name'])
               var_b = var_c.get_absolute_url
               link_v.append(var_b)
           elif popular_c['category'] == 'acses':
               product_c = Acses.objects.filter(slug= popular_c['name'])
               var_v +=list(product_c)
               var_c = get_object_or_404(Acses, slug= popular_c['name'])
               var_b = var_c.get_absolute_url
               link_v.append(var_b)
           elif popular_c['category'] == 'perf':
               product_c = Perf.objects.filter(slug= popular_c['name'])
               var_v += product_c
               var_c = get_object_or_404(Perf, slug= popular_c['name'])
               var_b = var_c.get_absolute_url
               link_v.append(var_b)
           elif popular_c['category'] == 'kompyutery':
               product_c = PC.objects.filter(slug= popular_c['name'])
               var_v += product_c
               var_c = get_object_or_404(PC, slug= popular_c['name'])
               var_b = var_c.get_absolute_url
               link_v.append(var_b)
           if var_v[0].category.prop_list != '':
                vs = var_v[0].category.prop_list.split(',')
    title = 'Сравнение - PCShop.uz'




    return render(request, '../../main/templates/versus.html', {'versus': var_v,
                                                                'vs':vs,
                                                                 'title' :title} )


def CraftAdd(request, big_category_slug, category_slug, slug):
    craft = Craft(request)
    craft.craft_add(product=slug, big_category_slug=big_category_slug, category_slug=category_slug)
    return redirect('cart:CraftDetail')


def CraftRemove(request, big_category_slug, product_slug):
    craft = Craft(request)
    craft.remove(big_category_slug, product_slug)
    return redirect('cart:CraftDetail')


def CraftDetail(request):
    craft = Craft(request)
    form = PCForm
    detail1 = ''
    detail2 = ''
    detail3 = ''
    detail4 = ''
    detail5 = ''
    detail6 = ''
    detail7 = ''
    detail8 = ''
    detail9 = ''
    price = [0, 0, 0, 0, 0, 0, 0, 0, 0]
    error_ram = ''
    error_cpu = ''
    cpu_socket = ''
    motherboard_socket = ''
    ram_ddr = ''
    motherboard_ddr = ''
    checker = ''

    if request.POST:
        if request.POST['property_1'] != '':
            item=get_object_or_404(Complecting,pk=request.POST['property_1'])
            craft.craft_add(product=item.slug, big_category_slug=item.maincategory.slug, category_slug=item.category.slug)
        elif 'cpu' in craft.craft:
            craft.remove('komplektuyishie', 'proc')

        if request.POST['property_2'] != '':
            item=get_object_or_404(Complecting,pk=request.POST['property_2'])
            craft.craft_add(product=item.slug, big_category_slug=item.maincategory.slug, category_slug=item.category.slug)
        elif 'ram' in craft.craft:
            craft.remove('komplektuyishie', 'ram')

        if request.POST['property_3'] != '':
            item=get_object_or_404(Complecting,pk=request.POST['property_3'])
            craft.craft_add(product=item.slug, big_category_slug=item.maincategory.slug, category_slug=item.category.slug)
        elif 'video' in craft.craft:
            craft.remove('komplektuyishie', 'video')

        if request.POST['property_4'] != '':
            item=get_object_or_404(Complecting,pk=request.POST['property_4'])
            craft.craft_add(product=item.slug, big_category_slug=item.maincategory.slug, category_slug=item.category.slug)
        elif 'hdd' in craft.craft:
            craft.remove('komplektuyishie', 'hdd')

        if request.POST['property_5'] != '':
            item=get_object_or_404(Complecting,pk=request.POST['property_5'])
            craft.craft_add(product=item.slug, big_category_slug=item.maincategory.slug, category_slug=item.category.slug)
        elif 'motherboard' in craft.craft:
            craft.remove('komplektuyishie', 'matb')

        if request.POST['property_6'] != '':
            item=get_object_or_404(Complecting,pk=request.POST['property_6'])
            craft.craft_add(product=item.slug, big_category_slug=item.maincategory.slug, category_slug=item.category.slug)
        elif 'bp_1' in craft.craft:
            craft.remove('komplektuyishie', 'bp_1')

        if request.POST['property_7'] != '':
            item=get_object_or_404(Complecting,pk=request.POST['property_7'])
            craft.craft_add(product=item.slug, big_category_slug=item.maincategory.slug, category_slug=item.category.slug)
        elif 'bp_2' in craft.craft:
            craft.remove('komplektuyishie', 'bp_2')

        if request.POST['property_8'] != '':
            item=get_object_or_404(Complecting,pk=request.POST['property_8'])
            craft.craft_add(product=item.slug, big_category_slug=item.maincategory.slug, category_slug=item.category.slug)
        elif 'coolers' in craft.craft:
            craft.remove('komplektuyishie', 'cool')

        if request.POST['property_9'] != '':
            item=get_object_or_404(Complecting,pk=request.POST['property_9'])
            craft.craft_add(product=item.slug, big_category_slug=item.maincategory.slug, category_slug=item.category.slug)
        elif 'dvd' in craft.craft:
            craft.remove('komplektuyishie', 'dvd')


    if 'cpu' in craft.craft:
        detail1 = get_object_or_404(Complecting, slug=craft.craft['cpu']['name'])
        price[0]=(detail1.price)
        cpu_socket=detail1.property_2
    if 'ram' in craft.craft:
        detail2 = get_object_or_404(Complecting, slug=craft.craft['ram']['name'])
        price[1] =(detail2.price)
        ram_ddr = detail2.property_1[:4]
    if 'video' in craft.craft:
        detail3 = get_object_or_404(Complecting, slug=craft.craft['video']['name'])

main/templates/cart.html
{% extends 'base.html' %} {% load filters %}
{% block content %}

  <!-- ********************** --> 
  <!--     I N T R O          -->
  <!-- ********************** --> 
  <div id="intro_2">
    <div id="intro_wrap">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
      <div class="container_12">
        <div id="breadcrumbs" class="grid_12">
          <a href="/">Магазин</a>
           &gt; <a href="/cart">Корзина</a>
        </div>
        <h1>Закупка</h1>
      </div>
    </div>
  </div>
  </div>
  </div>
   </div>
  <!-- end of intro -->


  <!-- ********************** --> 
  <!--      C O N T E N T     --> 
  <!-- ********************** -->
<div class="container">
        <div class="row">
          <div class="col-md-12"
  <div id="content" class="container_12">

    <div id="shopping_cart" class="grid_12">

      <form id="cart" class="clearfix" >
        <table class="s_table_1" width="100%" cellpadding="0" cellspacing="0" border="0">
          <tr>
            <th width="65">Удалить</th>
            <th width="60">Изоброжение</th>
            <th width="100">Товар</th>
            <th width="250">Подробности</th>
            <th>Количество</th>
            <th>Цена</th>
            <th>Общая цена</th>
          </tr>

            {% for item in cart_t %}

            {% with product=item.product %}

             <form action="{% url 'cart:CartAdd' product.maincategory product.slug %}" method="post" class="add"></form>

            <tr class="even">
            <td valign="middle"><a href="{% url 'cart:CartRemove' product.slug %}"><i class="fa fa-times" aria-hidden="true"></i></a></td>
            <td valign="middle"><a href="{{product.get_absolute_url}}"><img src="{{product.image.url}}" height="60px" alt="{{product.name}}" /></a></td>
            <td valign="middle"><a href="{{product.get_absolute_url}}"><strong>{{product.property_1}} {{product.name}}</strong></a></td>
            <td valign="middle"> {{product.property_1}} {{product.property_2}} {{product.property_3}} {{product.property_4}} {{product.property_5}}</td>
            <td valign="middle"><form action="{% url 'cart:CartAdd' product.maincategory.slug  product.slug %}" method="post" class="add">
              {{ item.update_quantity_form.quantity }}
              {{ item.update_quantity_form.update }}
              {% csrf_token %}
              <input type="submit" value="Пресчитать">
            </form>    </td>
              <td valign="middle">{{product.price|price_convert}}<span class="s_currency s_after"> сум</span></td>
              <td valign="middle"> {{item.total_price|price_convert}}<span class="s_currency s_after"> сум</span>

              </td>
            </tr>


          {% endwith %}
            {% endfor %}

        </table>
        <br />
        <p class="s_total"><strong>В сумме:</strong>  {{total_price|price_convert }}<span class="s_currency s_after"> сум</span></p>
        <p class="s_total"><strong>Доставка:</strong> 30 000<span class="s_currency s_after"> сум</span></p>
        <p class="s_total s_secondary_color last"><strong>Общий счет заказа:</strong>  {{total_price|price_convert_dos }}<span class="s_currency s_after"> сум</span></p>

        <div class="clear"></div>
        <br />

        <a class="s_button_1 s_ddd_bgr left" href="/notebooks"><span class="s_text">Продолжить закуп</span></a>
        <button class="s_button_1 s_main_color_bgr" type="submit"><span class="s_text">Оформить заказ</span></button>
        <a class="s_button_1 s_main_color_bgr" href=""><span class="s_text">Пересчитать</span></a>
      </form>

    </div>

    <div class="clear"></div>
    <br />
    <br />
    
  </div>
      </div> </div>
  <!-- end of content -->
{% endblock %}

main/templates/cart_col.html
{%load filters%}

      <div id="cart_side" class="s_box_1 s_cart_holder">
        <h2 class="s_secondary_color">Корзина</h2>
        <div id="cart_side_contents">


              {% for item in cart %}
                {% with product=item %}
                    <div class="s_cart_item">
                    <a id="hremove_95" class="s_button_remove" href="{% url 'cart:CartRemove' product.slug %}">&nbsp;</a>
                        <span class="block"> x{{item.quantity}} <a href="{{product.get_absolute_url}}"> <b>{{item.property_1}} {{product.name}}</b> </a></span>
                    </div>
                {% endwith %}
              {% endfor %}

          <span class="clear s_mb_15 border_eee"></span>
            <div class="s_total clearfix"><strong class="cart_module_total left">Общее</strong><span class="cart_module_total">{{ cart.get_total_price|price_convert }}<span class="s_currency s_after"> сум</span></span></div>
          <span class="clear s_mb_15"></span>
          <div class="align_center clearfix">
            <a class="s_button_1 s_secondary_color_bgr s_ml_0" href="/cart"><span class="s_text">Корзина</span></a>
            <a class="s_button_1 s_secondary_color_bgr" href="checkout.html"><span class="s_text">Оформить</span></a>
          </div>

        </div>
      </div>

main/templates/contacts.html
{% extends 'base.html' %} {% load static %} {%load filters%}
{% block content %}
<div class="row">
  <div class="container">
    <div class="col-md-8">
<h1>
Компьютерная техника и комплектующие для ПК
</h1>
<h2>
О нас.
  </h2>
<p>
  С 1998 года «PCShop group» осуществляет реализацию продукции ведущих производителей, а также сборку персональных компьютеров, графических станций и серверов. За это время мы завоевали доверие более 100 корпоративных клиентов, собрали более 10 000 компьютеров, а также создали солидную клиентскую базу.
 </p>     <h2>Миссия «PCShop group»</h2> <p>
  Миссия магазинов PCHop — дарить людям возможность приобретать компьютерную технику по низким ценам с качественным обслуживанием и гарантией, потому что мы считаем, что одним из важнейших качеств хорошего магазина является высокий уровень покупательского сервиса.
И мы стремимся к тому, чтобы наши клиенты доверяли нам, как к своим друзьям.
</p>
<h2>
Для удобства выбора
</h2>
<p>
  Мы стремимся предоставить максимум полезной информации о продаваемых товарах. Сайт PCShop.uz снабжен простыми и эффективными инструментами подбора товаров по техническим характеристикам. Например, в категории «ПК» вы можете задать сортировку по 11 важным параметрам. Мы готовы предложить 100% совместимые сопутствующие товары, аксессуары и расходные материалы.
</p>
<p>
  Удобная доставка по всему Узбекистану.
Все товары в нашем магазине продаются с доставкой.
Доставка в пределах Ташкента осуществляется в течении одного дня. В области предоставляется доставка течении 3х дней.
Любой из наших товаров вы можете приобрести в кредит даже без первого взноса.
</p>
<h2>
Структура компании
</h2>
<p>
  В PCShop входит три самостоятельной фирмы.
</p>
<ul style="list-style:round;">
  <li>PCShop - Осуществляет сборку персональных компьютеров, графических станций, серверов и совместимые сопутствующих товаров и расходных материалов.</li>
  <li>Home credit – Осуществляет реализацию бытовой техники, компьютеров и ноутбуков в кредит.</li>
  <li>inGame – Первый в Узбекистане Киберспортивный магаз</li>
  </ul>
</div>
    </div>
  </div>
{% endblock %}

main/templates/list.html
{% extends 'base.html' %}
 {% load filters %}
{% block content %}
  

  <!-- ********************** --> 
  <!--     I N T R O          -->
  <!-- ********************** --> 

  <div id="intro_2">
    <div id="intro_wrap">
      <div class="container">
       <div class="row">
         <div class="col-md-12">
      <div class="container_12">
        <div id="breadcrumbs" class="grid_12">
          <a href="/">Магазин</a>
          &gt;
          <a href="/{{products.0.maincategory.slug}}">{{products.0.maincategory.name}}</a>
          &gt;
          <a href="/{{products.0.category.slug}}">{{products.0.category.name}}</a>
        </div>
        <h1>{{products.0.category.name}}</h1>
      </div>
    </div>
  </div>
  </div>
    </div>
    </div>
  <!-- end of intro -->

  
  <!-- ********************** --> 
  <!--      C O N T E N T     -->
  <!-- ********************** -->
  <div class="container">
    <div class="row">
      <div id="content" class="container_16">
        <div class="col-md-3 col-sm-12">
         <div id="right_col" class="grid_4">
         {% include 'cart_col.html'%}
         {% include 'filter_col.html'%}
         </div>
         </div>
      </div>
        <div class="col-md-9 col-sm-12">
    <div id="category" class="grid_12">
    <!--
      <div class="s_subcategories s_grid_view s_listing clearfix">
        <div class="s_subcategory"> <a href=""><img src="images/category_100x100.jpg" title="Digital Cameras" alt="Digital Cameras" style="margin-bottom: 3px;" /></a> <a href="">Digital Cameras</a> </div>
        <div class="s_subcategory"> <a href=""><img src="images/category_100x100.jpg" title="Home Audio" alt="Home Audio" style="margin-bottom: 3px;" /></a> <a href="">Home Audio</a> </div>
        <div class="s_subcategory"> <a href=""><img src="images/category_100x100.jpg" title="Home Cinema" alt="Home Cinema" style="margin-bottom: 3px;" /></a> <a href="">Home Cinema</a> </div>
        <div class="s_subcategory"> <a href=""><img src="images/category_100x100.jpg" title="Cell Phones" alt="Cell Phones" style="margin-bottom: 3px;" /></a> <a href="">Cell Phones</a> </div>
        <div class="s_subcategory"> <a href=""><img src="images/category_100x100.jpg" title="MP3 Players" alt="MP3 Players" style="margin-bottom: 3px;" /></a> <a href="">MP3 Players</a> </div>
        <div class="s_subcategory"> <a href=""><img src="images/category_100x100.jpg" title="Car-Audio" alt="Car-Audio" style="margin-bottom: 3px;" /></a> <a href="">Car-Audio</a> </div>
        <div class="clear"></div>
      </div>
       -->
      <div id="listing_options">
        <div id="listing_sort" class="s_switcher">
          <span class="s_selected">Отсортировать</span>
          <ul class="s_options" style="display: none;">
            <li><a href="?sort=1">Названия A - Z</a></li>
            <li><a href="">Name Z - A</a></li>
            <li><a href="">Price Low &gt; High</a></li>
            <li><a href="">Price High &gt; Low</a></li>
            <li><a href="">Rating Highest</a></li>
            <li><a href="">Rating Lowest</a></li>
            <li><a href="">Model A - Z</a></li>
            <li><a href="">Model Z - A</a></li>
          </ul>
        </div>
        <div id="view_mode" class="s_nav">
          <ul class="clearfix">
            <li id="view_grid"><a href="?chos=True"><span class="s_icon"></span>Сеткой</a></li>
            <li id="view_list" class="s_selected"><a href="?chos=False"><span class="s_icon"></span>Списком</a></li>
            <form method="GET">{{form.chos.as_p}}</form>
          </ul>
        </div>
      </div>

      <div class="clear"></div>

      <div class="s_listing s_list_view clearfix">
        {% for product in products %}
        <div class="s_item clearfix">
          <div class="col-xs-3">
          <div class="grid_3 alpha"> <a class="s_thumb" href="{{ product.get_absolute_url }}"><img src="{% if product.image %}{{ product.image.url }}{% else %}{% endif %}" class="img-responsive" title="{{ product.name }}"  /></a> </div>
          </div>
          <div class="grid_9 omega">
          <div class="col-xs-8">

            <h3><a href="{{ product.get_absolute_url }}">{{ product.category }} {{ product.name }}</a></h3>
            <p class="s_model">{{product.property_1}}</p>

            <p class="s_description"> {% autoescape off %}{{ product.description|truncatechars_html:200 }} {% endautoescape %}</p>
            <a class="s_button_add_to_cart" href="{% url 'cart:CartAdd' product.maincategory.slug product.slug %}"><span class="s_icon_16"><span class="s_icon"></span>Добавить в корзину</span></a>
            </div>

          <div class="col-xs-1">
          <p class="s_price">{{ product.price|price_convert }}<span class="s_currency s_before"><br/>сум</span></p>
          </div>
            </div>
        </div>
        <div class="clear"></div>
        {% endfor %}
      </div>
      
      <div class="pagination">
        <div class="results">Showing 1 to 6 of 6 (1 Pages)</div>
      </div>
      
    </div>
    


    <!--  <div id="featured_side" class="s_box clearfix">
        <h2>Featured</h2>
        <div class="s_item s_size_1 clearfix">
          <a class="s_thumb" href="product.html"><img src="images/dummy/pic_8.jpg" width="38" height="38" alt="White football trainers" /></a>
          <h3><a href="product.html">White football trainers</a></h3>
          <p><a href="product.html"><span class="s_main_color"><span class="s_currency s_before">£</span>117.50</span></a></p>
        </div>
      </div>
    -->
    </div>
    </div>
    </div>


  <!-- end of content -->
  
  
  
{% endblock %}

main/templates/versus.html
{% extends 'base.html' %} {% load filters %}
{% block content %}

  <!-- ********************** --> 
  <!--     I N T R O          -->
  <!-- ********************** --> 
  <div id="intro_2">
    <div id="intro_wrap">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
      <div class="container_12">
        <div id="breadcrumbs" class="grid_12">
          <a href="/">Магазин</a>
           &gt; <a href="/cart">Сравнение</a>
        </div>
        <h1>Сравнение</h1>
      </div>
    </div>
  </div>
  </div>
  </div>
   </div>
  <!-- end of intro -->


  <!-- ********************** --> 
  <!--      C O N T E N T     --> 
  <!-- ********************** -->
<div class="container">
        <div class="row">
          <div class="col-md-12">
  <div id="content" class="container_12">

    <div id="shopping_cart" class="grid_12">
        <table class="s_table_1" cellpadding="0" cellspacing="0" border="0">
          <tr>
            <th width="20%">Свойство</th>
            {% for product in versus%}
            <th width="20%"><a href="{{product.get_absolute_url}}">{{product.name}}</a> <a href="{% url 'cart:VersusRemove' product.slug %}"><i class="fa fa-times" aria-hidden="true"></i></a></th>
            {%endfor%}
           <tr>
              <tr class="even">
              <td class="s_table_left_th" valign="middle">Фото</td>
            {% for product in versus%}
             <td valign="middle"><a href="{{product.get_absolute_url}}"><img class="s_table_1_img" src="{{product.image.url}}" height="60px" alt="{{product.name}}" /></a></td>
            {%endfor%}
            </tr>
              {% for prop in vs%}
              <tr class="even">
                <td class="s_table_left_th" valign="middle">{{prop}}</td>
                {% for product in versus%}
                <td valign="middle">{{product|vers_prop:forloop.parentloop.counter}}</td>
                {%endfor%}
            {%endfor%}
              </tr>
            <tr>
              <td class="s_table_left_th" valign="middle">Цена</td>
            {% for product in versus%}
              <td valign="middle">{{product.price|price_convert}} сум</td>
            {%endfor%}
          </tr>


        </table>

        <div class="clear"></div>
        <br />


    </div>
   </div>
    <div class="clear"></div>
    <br />
    <br />
    
  </div>
      </div> </div>
  <!-- end of content -->
{% endblock %}